{wood           : 17,
 stone          : 1,
 dir            : 3,
 cobblestone    : 4,
 oak_wood_plank : 5,
 berock         : 6,
 sand           : 12,
 gravel         : 13,
 gold_ore       : 14,
 iron_ore       : 15,
 coal_ore       : 16,
 oak_wood       : 17,
 sandstone      : 24,
 note_block     : 25,
 while_wool     : 35,
 gold           : 41,
 iron           : 42,
 double_stone   : 43,
 bricks         : 45,
 obsidia        : 49,
 diamond_ore    : 56,
 diamond        : 57,
 clay           : 82,
 glowstone      : 89,
 white_stained_glass : 95,
 double_oak     : 125,
 emerald_ore    : 129,
 emerald        : 133,
 quartz         : 155,
 white_clay     : 159,
 hardened_clay  : 172,
 block_of_coal  : 173,
 red_sandstone  : 179,
 white_concrete : 251}